name: ng_color_picker
description: Simple and lightweight color picker component for AngularDart
version: 1.0.0
homepage: https://jodinathan.github.io/ng_color_picker/

environment:
  sdk: ^3.2.0

dependencies:
  ngdart: ^8.0.0-dev.2
  ngrouter: ^4.0.0-dev.1
  ngforms: ^5.0.0-dev.1
  sass_builder: ^2.1.4
  change_notifier: ^0.24.0
  # dispose: ^0.0.7
  # stream_transform: ^2.0.0

dev_dependencies:  
  build_runner: ^2.1.2
  build_test: ^2.1.3
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
  test: ^1.24.0

dependency_overrides:
  build_modules: ^5.0.0
  analyzer: ^6.4.1

